import type { Config } from 'tailwindcss'

function cssVar(name: string) {
  return `rgb(var(--color-${name}) / <alpha-value>)`
}

const config: Config = {
  darkMode: 'class',
  content: ['./src/renderer/**/*.{ts,tsx,html}'],
  theme: {
    extend: {
      colors: {
        primary: cssVar('primary'),
        'primary-container': cssVar('primary-container'),
        'primary-fixed': cssVar('primary-fixed'),
        'primary-fixed-dim': cssVar('primary-fixed-dim'),
        'on-primary': cssVar('on-primary'),
        'on-primary-container': cssVar('on-primary-container'),
        'on-primary-fixed': cssVar('on-primary-fixed'),
        'on-primary-fixed-variant': cssVar('on-primary-fixed-variant'),
        secondary: cssVar('secondary'),
        'secondary-container': cssVar('secondary-container'),
        'secondary-fixed': cssVar('secondary-fixed'),
        'secondary-fixed-dim': cssVar('secondary-fixed-dim'),
        'on-secondary': cssVar('on-secondary'),
        'on-secondary-container': cssVar('on-secondary-container'),
        'on-secondary-fixed': cssVar('on-secondary-fixed'),
        'on-secondary-fixed-variant': cssVar('on-secondary-fixed-variant'),
        tertiary: cssVar('tertiary'),
        'tertiary-container': cssVar('tertiary-container'),
        'tertiary-fixed': cssVar('tertiary-fixed'),
        'tertiary-fixed-dim': cssVar('tertiary-fixed-dim'),
        'on-tertiary': cssVar('on-tertiary'),
        'on-tertiary-container': cssVar('on-tertiary-container'),
        'on-tertiary-fixed': cssVar('on-tertiary-fixed'),
        'on-tertiary-fixed-variant': cssVar('on-tertiary-fixed-variant'),
        error: cssVar('error'),
        'error-container': cssVar('error-container'),
        'on-error': cssVar('on-error'),
        'on-error-container': cssVar('on-error-container'),
        surface: cssVar('surface'),
        'surface-dim': cssVar('surface-dim'),
        'surface-bright': cssVar('surface-bright'),
        'surface-container-lowest': cssVar('surface-container-lowest'),
        'surface-container-low': cssVar('surface-container-low'),
        'surface-container': cssVar('surface-container'),
        'surface-container-high': cssVar('surface-container-high'),
        'surface-container-highest': cssVar('surface-container-highest'),
        'surface-variant': cssVar('surface-variant'),
        'surface-tint': cssVar('surface-tint'),
        'on-surface': cssVar('on-surface'),
        'on-surface-variant': cssVar('on-surface-variant'),
        background: cssVar('background'),
        'on-background': cssVar('on-background'),
        outline: cssVar('outline'),
        'outline-variant': cssVar('outline-variant'),
        'inverse-surface': cssVar('inverse-surface'),
        'inverse-on-surface': cssVar('inverse-on-surface'),
        'inverse-primary': cssVar('inverse-primary'),
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        gutter: '24px',
        margin: '32px',
        lg: '48px',
        xl: '80px',
      },
      fontFamily: {
        sans: ['"Noto Sans SC"', '"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      boxShadow: {
        ambient: '0 4px 12px rgba(107, 56, 212, 0.06)',
        'ambient-hover': '0 10px 25px rgba(107, 56, 212, 0.12)',
        floating: '0 8px 24px rgba(0, 0, 0, 0.06)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out',
      },
    },
  },
  plugins: [],
}

export default config
