import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./src/renderer/**/*.{ts,tsx,html}'],
  theme: {
    extend: {
      colors: {
        primary: '#6B38D4',
        'primary-container': '#8455EF',
        'primary-fixed': '#E9DDFF',
        'primary-fixed-dim': '#D0BCFF',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#FFFBFF',
        'on-primary-fixed': '#23005C',
        'on-primary-fixed-variant': '#5516BE',
        secondary: '#775A00',
        'secondary-container': '#FEC300',
        'secondary-fixed': '#FFDF99',
        'secondary-fixed-dim': '#F7BE00',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#6D5200',
        'on-secondary-fixed': '#251A00',
        'on-secondary-fixed-variant': '#5A4300',
        tertiary: '#855000',
        'tertiary-container': '#A76500',
        'tertiary-fixed': '#FFDCBB',
        'tertiary-fixed-dim': '#FFB869',
        'on-tertiary': '#FFFFFF',
        'on-tertiary-container': '#FFFBFF',
        'on-tertiary-fixed': '#2C1700',
        'on-tertiary-fixed-variant': '#673D00',
        error: '#BA1A1A',
        'error-container': '#FFDAD6',
        'on-error': '#FFFFFF',
        'on-error-container': '#93000A',
        surface: '#F9F9FF',
        'surface-dim': '#D3DAEA',
        'surface-bright': '#F9F9FF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F0F3FF',
        'surface-container': '#E7EEFE',
        'surface-container-high': '#E2E8F8',
        'surface-container-highest': '#DCE2F3',
        'surface-variant': '#DCE2F3',
        'surface-tint': '#6D3BD7',
        'on-surface': '#151C27',
        'on-surface-variant': '#494454',
        background: '#F9F9FF',
        'on-background': '#151C27',
        outline: '#7B7486',
        'outline-variant': '#CBC3D7',
        'inverse-surface': '#2A313D',
        'inverse-on-surface': '#EBF1FF',
        'inverse-primary': '#D0BCFF',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        gutter: '24px',
        margin: '32px',
        lg: '48px',
        xl: '80px',
      },
      fontFamily: {
        sans: ['"Alibaba PuHuiTi 3.0"', '"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      boxShadow: {
        ambient: '0 4px 12px rgba(107, 56, 212, 0.06)',
        'ambient-hover': '0 10px 25px rgba(107, 56, 212, 0.12)',
        floating: '0 8px 24px rgba(0, 0, 0, 0.06)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out',
      },
    },
  },
  plugins: [],
}

export default config
